# buildbot/buildbot-worker

# please follow docker best practices
# https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/

# Provides a base Debian image with latest buildbot worker installed

FROM        debian:jessie
MAINTAINER  mariadb.com

USER root

COPY . /usr/src/buildbot-worker
COPY docker/buildbot.tac /buildbot/buildbot.tac

ENV  image_built 2017-08-10

# This will make apt-get install without question
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get -y install software-properties-common python-software-properties lsb-release

RUN add-apt-repository "deb http://security.debian.org $(lsb_release -c | awk '{print $2}')/updates main contrib" -s
RUN add-apt-repository "deb http://ftp.debian.org/debian $(lsb_release -c | awk '{print $2}') main contrib" -s

RUN apt-get update && apt-get -y upgrade && \
    apt-get -y install -q apt-utils build-essential git python-dev libffi-dev libssl-dev curl
RUN rm -rf /var/lib/apt/lists/*

# Get the latest pip (newer than python-pip; old versions have security issues)
RUN curl -Lo get-pip.py https://bootstrap.pypa.io/get-pip.py && python get-pip.py

# https://github.com/Yelp/dumb-init
RUN curl -Lo /usr/local/bin/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.1.3/dumb-init_1.1.3_amd64 && \
    chmod +x /usr/local/bin/dumb-init

RUN pip install virtualenv && \
    pip --no-cache-dir install twisted[tls] && \
    pip install /usr/src/buildbot-worker

RUN useradd -ms /bin/bash buildbot && chmod 755 /buildbot && chown -R buildbot:buildbot /buildbot

RUN apt-get update && apt-get -y build-dep mariadb-server
RUN apt-get update && apt-get -y install libcurl4-openssl-dev pkg-config libpthread-stubs0-dev debhelper dh-make dpkg-dev devscripts
RUN apt-get -y install dh-systemd dpatch gdb libcrack2-dev libkrb5-dev libnuma-dev libsnappy-dev libsystemd-dev libxml2-dev unixodbc-dev uuid-dev

USER buildbot
WORKDIR /buildbot
CMD ["/usr/local/bin/dumb-init", "twistd", "-ny", "buildbot.tac"]

