# buildbot/buildbot-worker

# please follow docker best practices
# https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/

# Provides a base CentOS (7) image with latest buildbot worker installed

FROM        centos
MAINTAINER  mariadb.com

USER root

COPY . /usr/src/buildbot-worker
COPY docker/buildbot.tac /buildbot/buildbot.tac

ENV image_built 2017-07-31

# Install security updates and required packages
RUN yum update -y && \
    yum install -y epel-release deltarpm && \
    yum groupinstall -y "Development Tools" && \
    yum install -y git curl gcc python python-devel openssl-devel && \
    yum clean all

# Get the latest pip (newer than python-pip; old versions have security issues)
RUN curl -Lo get-pip.py https://bootstrap.pypa.io/get-pip.py && \
    python get-pip.py

# https://github.com/Yelp/dumb-init
RUN curl -Lo /usr/local/bin/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.1.3/dumb-init_1.1.3_amd64 && \
    chmod +x /usr/local/bin/dumb-init

RUN pip install virtualenv && \
    pip --no-cache-dir install service_identity pycrypto && \
    pip --no-cache-dir install twisted[tls] && \
    pip install /usr/src/buildbot-worker

RUN useradd -ms /bin/bash buildbot && chown -R buildbot /buildbot

USER buildbot
WORKDIR /buildbot

CMD ["/usr/local/bin/dumb-init", "twistd", "-ny", "buildbot.tac"]

USER root

RUN yum-builddep -y mariadb
RUN yum install -y glibc-devel

# USER buildbot
# WORKDIR /buildbot
# RUN buildbot-worker create-worker . bb04.mariadb.net:9989 centos-worker f02428f2r2
# ENTRYPOINT ["/usr/local/bin/buildbot-worker"]
# CMD ["start", "--nodaemon"]

